name: Publish to npm on Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Validate package version
        run: |
          CURRENT_VERSION=$(npm show $(node -p "require('./package.json').name") version || echo "0.0.0")
          NEW_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
            echo "The version $NEW_VERSION is already published on npm. Skipping npm publish."
            exit 1
          fi

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm publish --access public --loglevel verbose
